//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public int departmentId { get; set; }
        public string Username { get; set; }
        public string ProfilePic { get; set; }
        public string Password { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
